# Generated by Django 3.1.1 on 2020-09-18 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('description', models.TextField(blank=True, default=None, null=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Цена')),
                ('name', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('discount', models.IntegerField(default=0)),
                ('short_description', models.TextField(blank=True, default=None, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория товара', 'verbose_name_plural': 'Категория товаров'},
        ),
        migrations.RemoveField(
            model_name='notebook',
            name='category',
        ),
        migrations.RemoveField(
            model_name='notebook',
            name='description',
        ),
        migrations.RemoveField(
            model_name='notebook',
            name='id',
        ),
        migrations.RemoveField(
            model_name='notebook',
            name='image',
        ),
        migrations.RemoveField(
            model_name='notebook',
            name='price',
        ),
        migrations.RemoveField(
            model_name='notebook',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='notebook',
            name='title',
        ),
        migrations.RemoveField(
            model_name='smartphone',
            name='category',
        ),
        migrations.RemoveField(
            model_name='smartphone',
            name='description',
        ),
        migrations.RemoveField(
            model_name='smartphone',
            name='id',
        ),
        migrations.RemoveField(
            model_name='smartphone',
            name='image',
        ),
        migrations.RemoveField(
            model_name='smartphone',
            name='price',
        ),
        migrations.RemoveField(
            model_name='smartphone',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='smartphone',
            name='title',
        ),
        migrations.AddField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products_images/')),
                ('is_main', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.product')),
            ],
            options={
                'verbose_name': 'Фотография',
                'verbose_name_plural': 'Фотографии',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='product_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mainapp.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='smartphone',
            name='product_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mainapp.product'),
            preserve_default=False,
        ),
    ]
